# Generated by Django 3.2.8 on 2021-10-13 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.PositiveIntegerField(editable=False, primary_key=True, serialize=False)),
                ('deleted', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('comment', 'Comment'), ('story', 'Story'), ('job', 'Job'), ('poll', 'Poll'), ('pollopt', 'Poll Option')], default='comment', max_length=15)),
                ('time', models.PositiveIntegerField(blank=True, null=True)),
                ('dead', models.BooleanField(default=False)),
                ('kids', models.TextField(blank=True, null=True)),
                ('descendants', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('parts', models.TextField(null=True)),
                ('score', models.PositiveIntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('text', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('delay', models.PositiveIntegerField(blank=True, null=True)),
                ('created', models.PositiveIntegerField()),
                ('karma', models.PositiveIntegerField()),
                ('about', models.CharField(blank=True, max_length=500)),
                ('submitted', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.PositiveIntegerField(editable=False, primary_key=True, serialize=False)),
                ('deleted', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('comment', 'Comment'), ('story', 'Story'), ('job', 'Job'), ('poll', 'Poll'), ('pollopt', 'Poll Option')], default='comment', max_length=15)),
                ('time', models.PositiveIntegerField(blank=True, null=True)),
                ('dead', models.BooleanField(default=False)),
                ('kids', models.TextField(blank=True, null=True)),
                ('descendants', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('score', models.PositiveIntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('text', models.CharField(blank=True, max_length=500)),
                ('url', models.URLField(blank=True)),
                ('by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.user')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PollOption',
            fields=[
                ('id', models.PositiveIntegerField(editable=False, primary_key=True, serialize=False)),
                ('deleted', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('comment', 'Comment'), ('story', 'Story'), ('job', 'Job'), ('poll', 'Poll'), ('pollopt', 'Poll Option')], default='comment', max_length=15)),
                ('time', models.PositiveIntegerField(blank=True, null=True)),
                ('dead', models.BooleanField(default=False)),
                ('kids', models.TextField(blank=True, null=True)),
                ('score', models.PositiveIntegerField(blank=True, null=True)),
                ('text', models.CharField(blank=True, max_length=500)),
                ('by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.user')),
                ('parent', models.ForeignKey(limit_choices_to=models.Q(('type', 'Poll')), on_delete=django.db.models.deletion.CASCADE, to='news.poll')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='poll',
            name='by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.user'),
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.PositiveIntegerField(editable=False, primary_key=True, serialize=False)),
                ('deleted', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('comment', 'Comment'), ('story', 'Story'), ('job', 'Job'), ('poll', 'Poll'), ('pollopt', 'Poll Option')], default='comment', max_length=15)),
                ('time', models.PositiveIntegerField(blank=True, null=True)),
                ('dead', models.BooleanField(default=False)),
                ('kids', models.TextField(blank=True, null=True)),
                ('score', models.PositiveIntegerField(blank=True, null=True)),
                ('text', models.TextField(blank=True, max_length=500)),
                ('url', models.URLField(blank=True)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.user')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.PositiveIntegerField(editable=False, primary_key=True, serialize=False)),
                ('deleted', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('comment', 'Comment'), ('story', 'Story'), ('job', 'Job'), ('poll', 'Poll'), ('pollopt', 'Poll Option')], default='comment', max_length=15)),
                ('time', models.PositiveIntegerField(blank=True, null=True)),
                ('dead', models.BooleanField(default=False)),
                ('kids', models.TextField(blank=True, null=True)),
                ('object_id', models.PositiveIntegerField()),
                ('text', models.CharField(blank=True, max_length=500)),
                ('by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.user')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
    ]
