# Generated by Django 3.2.8 on 2021-11-15 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='job',
            name='text',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='poll',
            name='text',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='polloption',
            name='text',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='story',
            name='text',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
